sonar.projectKey=hobsojam_muncher
sonar.organization=hobsojam
sonar.sources=src
sonar.cfamily.compile-commands=bw-output/compile_commands.json
sonar.exclusions=**/*.md
sonar.coverage.exclusions=src/main.c
sonar.coverageReportPaths=coverage.xml
